######################
##    CAN Config    ##
######################

# Interface

/receiver_interface:    "can0"
/transmitter_interface: "can0"

# Topics
# in ROS, dictionaries must have string keys
#/incoming_ids:          {"300": "turntableEncoder",
#                         "301": "shoulderEncoder",
#                         "302": "elbowEncoder",
#                         "303": "wristPitchEncoder",
#                         "304": "wristRollEncoder"}
/incoming_ids:          {"301": "shoulderEncoder",
                         "302": "elbowEncoder",
                         "303": "wristPitchEncoder"}
/output_topics:         ["/encoders"]
