######################
##    CAN Config    ##
######################

# Interface
/receiver_interface:    "vcan0"
/transmitter_interface: "vcan0"

# Topics
# in ROS, dictionaries must have string keys
/incoming_ids:          {"200": "limitSwitches",
                         "300": "armJointEncoder1",
                         "301": "armJointEncoder2",
                         "302": "armJointEncoder3",
                         "303": "armJointEncoder4",
                         "304": "armJointEncoder5",
                         "305": "endEffectorEncoder"}
/output_topics:         ["/absoluteEncoders",
                         "/relativeEncoders",
                         "/limitSwitches"]
